// Code generated by MockGen. DO NOT EDIT.
// Source: main/develop/dev01 (interfaces: INtp)

// Package mock_dev01 is a generated GoMock package.
package mock_dev01

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockINtp is a mock of INtp interface.
type MockINtp struct {
	ctrl     *gomock.Controller
	recorder *MockINtpMockRecorder
}

// MockINtpMockRecorder is the mock recorder for MockINtp.
type MockINtpMockRecorder struct {
	mock *MockINtp
}

// NewMockINtp creates a new mock instance.
func NewMockINtp(ctrl *gomock.Controller) *MockINtp {
	mock := &MockINtp{ctrl: ctrl}
	mock.recorder = &MockINtpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINtp) EXPECT() *MockINtpMockRecorder {
	return m.recorder
}

// GetTime mocks base method.
func (m *MockINtp) GetTime() (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTime indicates an expected call of GetTime.
func (mr *MockINtpMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockINtp)(nil).GetTime))
}
